notifications:
  webhooks:
    - https://webhook.commit-email.info/

services:
  - docker

matrix:
  include:
    - name: Ubuntu 18.04
      env: TYPE=ubuntu-18.04
    - name: opencv-glib master
      env: TYPE=opencv-glib-master

install:
  - docker build
      -t red-data-tools/red-opencv-${TYPE}
      -f travis/Dockerfile.${TYPE}
      .

script:
  - docker run
      --interactive
      --tty
      red-data-tools/red-opencv-${TYPE}
      bundle exec rake
